[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
line_length = 120
include_trailing_comma = true

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 120
disable = "C0114, R1705, C0103"

[tool.pytest.ini_options]
addopts = "-n auto -vv --cov=. --cov-report term-missing --cov-fail-under 98"
python_files = "tests/test_*.py"
